### ISSUE TITLE
plans to support Slack Blocks

### ISSUE THREAD

**Issue by smenzer** [laravel/slack-notification-channel#12]
Are there plans to support the new Slack Blocks any time soon? Just wondering if I should hack it myself for now or wait for this package to natively support them.

https://api.slack.com/changelog/2018-12-a-bric-a-brac-of-broadcasts-built-with-blocks

Thanks!

**Comment by driesvints** [comment]
Feel free to do a proposal

**Comment by driesvints** [comment]
Going to close this since the PR was rejected.

**Comment by nathanheffley** [comment]
In case anybody comes here wishing for Slack Blocks support, I created a package that extends this one and adds support for sending Blocks (or just sending notifications exactly like you would do in this package).

You can check it out on [GitHub](https://github.com/nathanheffley/laravel-slack-blocks) or [Packagist](https://packagist.org/packages/nathanheffley/laravel-slack-blocks).

**Comment by driesvints** [comment]
@nathanheffley nice. Good job!

**Comment by miken32** [comment]
This feature was implemented in #64. Would have been nice if the above PR hadn't been rejected 3 years ago, but better late than never I guess?

**Comment by nathanheffley** [comment]
@miken32 the new PR is a much nicer implementation, and back in 2019 it wasn't quite as certain that the new Blocks format would stick around long enough to make adding it to this package worth it, no need to necro a 4yo thread now that it's being added 🙂
