### ISSUE TITLE
slack warning message

### ISSUE THREAD

**Issue by dalsword** [laravel/slack-notification-channel#16]
I am using laravel version 5.8. What is the proper way to send a warning message to slack? The following code does not generate a warning message...

```
public function toSlack($notifiable)
    {
        return (new SlackMessage)
            ->content('One of your invoices has been paid!')
            ->warning();
    }
```

**Comment by nathanheffley** [comment]
I don't believe that Slack messages themselves actually use the color setting. Only Slack attachments use it: https://api.slack.com/docs/message-attachments
