### ISSUE TITLE
Not possible to use "Date" as the name of a field

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/slack-notification-channel#22]
Very simple issue to describe. The `SlackAttachment@field` method checks if the `$title` is callable using `is_callable`. If you use 'Date' as a field name (or any other name of a global function), it'll be used as a function instead of a string. Example:

```php
$attachment->field('Date', $someDate);
```

Leads to

> date() expects parameter 1 to be string, object given

`is_callable` is not a good way to overload the method, and it should be changed. For example, using an extra boolean parameter to indicate the first argument should be used as a callable.

**Comment by driesvints** [comment]
Please fill out the issue template.
