### ISSUE TITLE
Unable to disable link and media unfurling

### ISSUE THREAD

**Issue by xclose** [laravel/slack-notification-channel#30]
- Slack Notification Channel Version: 2.0.2
- Laravel Version: 6.0.3
- PHP Version: 7.2.26
- Database Driver & Version:

### Description:
Disabling link unfurling in slack messages does not work. Optional paramters with value of false gets dropped by array_filter when building json payload in SlackWebhookChannel. Slack ignores string values for unfurl_media and unfurl_links.

### Steps To Reproduce:
Create new SlackMessage with a full valid url, set unfurlLinks(false), notify slack channel.

**Comment by driesvints** [comment]
Please provide code examples.
