### ISSUE TITLE
"From" is not supported

### ISSUE THREAD

**Issue by chimit** [laravel/slack-notification-channel#34]
- Slack Notification Channel Version: 2.0.2
- Laravel Version: 6.15.1
- PHP Version: 7.4
- Database Driver & Version:

### Description:
The method `from` is not supported.

### Steps To Reproduce:
```php
return (new SlackMessage)
    ->from('MyBot', ':robot_face:')
    ->to('#general')
    ->content('Hi!');
```

**Comment by driesvints** [comment]
It is? Please give some more info here. What exactly isn't working for you?

**Comment by chimit** [comment]
Apparently, it's a [legacy protocol](https://api.slack.com/legacy/custom-integrations/incoming-webhooks). A `from` method simply doesn't work. Slack always displays an app username and avatar.

> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.
> https://api.slack.com/messaging/webhooks

**Comment by driesvints** [comment]
When did they drop support for this? Can you link to any changelogs, blog posts, etc?

**Comment by chimit** [comment]
Hm... I'm not familiar with the Slack API, but if I follow instructions from the [Slack log channel documentation](https://laravel.com/docs/7.x/logging#configuration) and use the [link](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) from that page it throws me to the "Incoming WebHooks" app page. If I create hooks there everything works perfectly.

But the link on the [Slack Notifications page](https://laravel.com/docs/7.x/notifications#slack-notifications) throws me to the absolutely [another page](https://api.slack.com/incoming-webhooks) that asks me to create a new app. It gives me a webhook URL as well, but if I use it the `from()` method is ignored by Slack.

So if you use the existing "Incoming WebHooks" app you can use custom icons and names, but if you create your own app with webhooks you can't customize icons and names. So the link on [this page](https://laravel.com/docs/7.x/notifications#slack-notifications) is misleading.

Please, correct me if I'm wrong.

**Comment by driesvints** [comment]
I'm currently using an incoming webhook in an app with the `from` method configured so I think there might be something we're missing here. If you can ever pinpoint the problem feel free to report back and we'll re-open.

**Comment by shino47** [comment]
> Hm... I'm not familiar with the Slack API, but if I follow instructions from the [Slack log channel documentation](https://laravel.com/docs/7.x/logging#configuration) and use the [link](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) from that page it throws me to the "Incoming WebHooks" app page. If I create hooks there everything works perfectly.
> 
> But the link on the [Slack Notifications page](https://laravel.com/docs/7.x/notifications#slack-notifications) throws me to the absolutely [another page](https://api.slack.com/incoming-webhooks) that asks me to create a new app. It gives me a webhook URL as well, but if I use it the `from()` method is ignored by Slack.
> 
> So if you use the existing "Incoming WebHooks" app you can use custom icons and names, but if you create your own app with webhooks you can't customize icons and names. So the link on [this page](https://laravel.com/docs/7.x/notifications#slack-notifications) is misleading.
> 
> Please, correct me if I'm wrong.

@chimit you are right. There are two different ways to integrate Slack to your project: [creating an app](https://api.slack.com/incoming-webhooks) and integrating the existing [Incoming WebHooks](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) app. If you create an app, you can't use the `from`, `to` and `image` methods, but you still can customize the _from_ name and image here: 

https://api.slack.com/apps

Then, scroll down to Display Information and there is it.

Using the existing _Incoming WebHooks_ is not recomended, as it uses a [legacy custom integration](https://api.slack.com/legacy/custom-integrations/incoming-webhooks), as @chimit pointed.

**Comment by chimit** [comment]
Thanks for the clarification, @shino47!

It is worth mentioning that customizing name and image in your own app is not as flexible as in legacy Incoming WebHooks because you can't do it dynamically from your code.

**Comment by driesvints** [comment]
@chimit done: https://github.com/laravel/docs/pull/5964

Thanks for clarifying that.
