### ISSUE TITLE
Driver not supported when slack notification is implemented with queue jobs

### ISSUE THREAD

**Issue by pedmindset** [laravel/slack-notification-channel#38]
- Slack Notification Channel Version: 2.1
- Laravel Version: 6.4
- PHP Version: 7.4
- Database Driver & Version: Mysql v 8

### Description:
(Driver [slack] not supported) Driver not supported when slack notification is implemented with queue jobs. 

Everything works when not implemented with queue.

**Comment by driesvints** [comment]
I'm using queued Slack notifications in production atm. 

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
