### ISSUE TITLE
No upgrade guide for upgrading from v2 to v3

### ISSUE THREAD

**Issue by introwit** [laravel/slack-notification-channel#69]
### Slack Notification Channel Version

2.5.0

### Laravel Version

10

### PHP Version

8.1

### Description

Seems like the way to generate or write a slack notification has completely changed in v3. For example currently in v2, the `content` method is used, while in v3 it seems like it has been replaced with a new method called `text` ? Also, seems like configuration has changed drastically as well. For example, currently no tokens for a bot are required to get going. We can just have a `routeNotificationForSlack` method on the `User` model and it returns a slack hook url. It would be helpful and hence would like to request for an upgrade guide if possible. The PRs linked in the release section also doesn't have any helpful context for managing user-land code during the upgrade. Thank you for all the work being put in to manage this repo 🚀 

### Steps To Reproduce

couldn't find the discussions tab hence had to create an issue.

**Comment by driesvints** [comment]
Hi there, I sent in a PR to add an upgrade guide. It basically boils down to you rewriting your notifications to the new way that's documented. If that's not clear, please answer on the PR. Thanks
