### ISSUE TITLE
Add colored bars to sections/blocks

### ISSUE THREAD

**Issue by realtebo** [laravel/slack-notification-channel#75]
I know slack can decorate messaging using colored vertical bar, like the follow

![image](https://github.com/laravel/slack-notification-channel/assets/1268699/3ccc97d9-7659-4818-84e1-e4ec7f35bdf4)

I suggest / request to add ability to this package to set colored bars

**Comment by driesvints** [comment]
welcoming prs, thanks

**Comment by realtebo** [comment]
I noticed there is already code for SlackAttachment. It's the one able to have a colored sidebar

I now think so this feature is already on

Could someone please document how to use?
