### ISSUE TITLE
Please document how to use SlackAttacments

### ISSUE THREAD

**Issue by realtebo** [laravel/slack-notification-channel#76]
> Please, don't close this Issue telling to open a PR: I am here because i have no idea on how to use an undocumented feature of this packges

I can see  the class  `vendor/laravel/slack-notification-channel/src/Messages/SlackAttachment.php` in my project.

I would like to add an attachment, but the only way to use is via  `vendor/laravel/slack-notification-channel/src/Slack/SlackMessage.php`

But this is not the class we (and the doc) use, because we (and the dodc) are instead using `vendor/laravel/slack-notification-channel/src/Slack/SlackMessage.php` 

Actually I'm trying to understand the code and if there is a way to use SlackAttachment

It's undocumented

And I cannot create a docuementation PR because I'm not able to document how to use a thing I have no idea how to use.

**Comment by jbrooksuk** [comment]
The `Messages` namespace is now deprecated. You should switch to the new Block Kit notifications which is Slack's preferred API.

However, you can refer to a previous version of the Laravel documentation to see how `SlackAttachment` is used. https://laravel.com/docs/9.x/notifications#slack-attachments
