### ISSUE TITLE
Need support for parse=none, parse=full, etc

### ISSUE THREAD

**Issue by ryancwalsh** [laravel/slack-notification-channel#8]
Thank you so much for this library. Very useful!

For your next release, I'm wondering if you'd consider adding support for https://api.slack.com/docs/message-formatting#parsing_modes

E.g. I'd love to be able to specify a `parse` mode (string property) on https://github.com/laravel/slack-notification-channel/blob/1.0/src/Messages/SlackMessage.php 

And then have https://github.com/laravel/slack-notification-channel/blob/1.0/src/Channels/SlackWebhookChannel.php#L55 add it to the payload.

Thanks for the great work!

**Comment by ryancwalsh** [comment]
In addition to or instead of what I suggested above, it would be nice (far more flexible and future-proof) to have a way to edit or append custom key-value pairs to the JSON payload: https://github.com/laravel/slack-notification-channel/blob/1.0/src/Channels/SlackWebhookChannel.php#L55

That way, even when Slack adds new options, this library could support them.

**Comment by nathanheffley** [comment]
According to the notice at the top of the [message formatting page](https://api.slack.com/docs/message-formatting) you linked, that information is mostly out of date so I don't think it would make sense to support it now.

Instead you should start using the new Block Kit system which allows for very rich notifications, and I just created PR #13 to add support for them in this package!

**Comment by driesvints** [comment]
Going to close this as the PR was rejected.
