### ISSUE TITLE
InputBlock missing.

### ISSUE THREAD

**Issue by GovertJansen** [laravel/slack-notification-channel#83]
I am creating a slack message, now I want to add an input text. But it turns out, the inputBlock doesn't exist at all. I see that there has been a question about this before, the issue has been closed but no solution has been found.

Why wasn't this added?

I like to hear it.

Kind regards, Govert

**Comment by crynobone** [comment]
See https://github.com/laravel/slack-notification-channel/pull/13#issuecomment-473663352
