### ISSUE TITLE
Unable to set $elements values in Laravel Slack notification block classes

### ISSUE THREAD

**Issue by sedwardsgt** [laravel/slack-notification-channel#93]
### Slack Notification Channel Version

3.2.0

### Laravel Version

11.9.2

### PHP Version

8.2

### Database Driver & Version

mongodb/laravel-mongodb v4.4

### Description

I am converting a Laravel app from using  [Nathanhelfley/laravel-slack-blocks](https://github.com/nathanheffley/laravel-slack-blocks) to using the built in [Illuminate\Notifications\Slack\BlockKit\Blocks](https://github.com/laravel/slack-notification-channel) blocks, and I can't figure out how to pass in the `$elements` value. For instance, with a `SlackBlock` class, I would do this for a context block;
```
        $block->elements([
            [
                'type' => 'mrkdwn',
                'text' => "Pursuit: *{$this->activityModel->target->name}*",
            ],
        ]);
```
However, with the `ContextBlock` class, there is no interface to pass in the entire element (e.g. `type => markdown`) because there is no setter for `$elements` and it is protected. The same is true for the other block types. How do I pass in the other values for a block other than the text and the id?

Per [one suggestion](https://laracasts.com/discuss/channels/laravel/how-to-set-elements-values-in-laravel-slack-notification-block-classes?page=1&replyId=939830), the correct implementation is something like this
```
$contextBlock = new ContextBlock();
$contextBlock->text(new MarkdownText("Pursuit: *{$this->activityModel->target->name}*"));
Add the block to your Slack message:
use Illuminate\Notifications\Slack\SlackMessage;

$slackMessage = (new SlackMessage)
    ->blocks(function ($block) use ($contextBlock) {
        $block->context($contextBlock);
    });
```
But there are two problems
- The `MarkdownText` class doesn't exist
- the `TextObject` class does, and it has a `markdown()` setter. However, the `text()` method takes a string, not an object.

Something like this doesn't work, for the same reason
```
        $block = new ContextBlock();

        $text_block = new TextObject("Pursuit: *{'My pursuit text}*");
        $text_block->markdown();

        $block->text($text_block);
```
But it's not just the `markdown` property. If you look at the doc block for the `$elements` property in [ActionsBlock](https://github.com/laravel/slack-notification-channel/blob/b783be6d9856020f27dc76468ecd092d2a99e7a4/src/Slack/BlockKit/Blocks/ActionsBlock.php), you see
```
    /**
     * An array of interactive element objects - buttons, select menus, overflow menus, or date pickers.
     *
     * There is a maximum of 25 elements in each action block.
     *
     * @var \Illuminate\Notifications\Slack\Contracts\ElementContract[]
     */
    protected array $elements = [];
```
which indicates to me that there somewhere is a way to add to those elements (up to 25), since the [Slack Blocks Reference](https://api.slack.com/reference/block-kit/blocks) indicates that there are many more things that can be added other than what these block kit classes allow.

As another example, the [ActionsBlock](https://github.com/laravel/slack-notification-channel/blob/3.x/src/Slack/BlockKit/Blocks/ActionsBlock.php) has a `button()` method,  but all it does is pass the text to the button:
```
    public function button(string $text): ButtonElement
    {
        return tap(new ButtonElement($text), function (ButtonElement $button) {
            $this->elements[] = $button;
        });
    }
```

with no option to pass the url. Do I have to somehow override that with a custom [ButtonElement](https://github.com/laravel/slack-notification-channel/blob/3.x/src/Slack/BlockKit/Elements/ButtonElement.php)?

Yes, I've seen the [Laravel Notifications docs](https://laravel.com/docs/11.x/notifications#formatting-slack-notifications), but that doesn't really answer this question, either (unless I'm missing something).

So it seems there is no way to build the blocks with all of the `$elements` values. Apologies if this is not a bug and I'm just mis-reading the code, but if it is a feature, some guidance would be appreciated.

### Steps To Reproduce

1. Implement `SlackMessage` class
2. Attempt to add items to the `$elements` array

See above for examples

**Comment by driesvints** [comment]
Thanks @sedwardsgt. Again assigning @jbrooksuk but highly unlikely he'll be able to help any time soon. Would appreciate PR's if anything can be improved here. Thanks.

**Comment by nathanheffley** [comment]
@sedwardsgt does something like this not work?

```
use Illuminate\Notifications\Slack\BlockKit\Blocks\ContextBlock;
use Illuminate\Notifications\Slack\SlackMessage;

$slackMessage = (new SlackMessage)
    ->contextBlock(function (ContextBlock $block) {
        $block->text("Pursuit: *{$this->activityModel->target->name}*")->markdown();
    });
```

**Comment by nathanheffley** [comment]
The API of this implementation is quite a bit different from my package's implementation. You will probably be served better by reading the docs and recreating the messages following the doc examples than trying to convert the code used for my package.

**Comment by sedwardsgt** [comment]
Yeah, that's what I ended up doing. 

To answer your question above, yes, that was what I ended up doing.

However, it seems that there are many options available for Slack message customization that are not available via the new implementation, that are allowed by allowing direct access to the `elements` array.

**Comment by princejohnsantillan** [comment]
I believe this update https://github.com/laravel/slack-notification-channel/pull/98 will help with this issue. You should now be able to use anything you find in https://app.slack.com/block-kit-builder.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
